security:
    #  Hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    #  Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    #  Pare-feu de sécurité
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password

            logout:
                path: app_logout
                # redirection possible :
                # target: /

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours
                path: /

    #  Contrôle d'accès par rôle
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    #  Hiérarchie des rôles (facultatif mais recommandé)
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PHOTOGRAPHE, ROLE_USER]
        ROLE_PHOTOGRAPHE: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
